_base: [queries/proj_queries, stories/proj]

builder:
  _type: random
path: data/proj10.json

seed: 69

name: Project685


spec-limit: 1 # how many specs use per story (selected randomly)
#difficulty: easy


